# Combine data
Filtered survey data, weights, hooks, and transformed variables

In [14]:
import pandas as pd

# load all data sources

survey_data = pd.read_csv('../data/intermediate/01_filtered_renamed_survey_data.csv').set_index('id')
hooks = pd.read_csv('../data/intermediate/03_survey_population_hooks.csv').set_index('id')
transformed_vars = pd.read_csv('../data/intermediate/04_transformed_variables.csv').set_index('id')
weights = pd.read_csv('../data/intermediate/03_survey_weights.csv').set_index('id')

In [16]:
data = survey_data.join(hooks).join(transformed_vars).join(weights)

In [18]:
data.head()

,year,q01_happy,q02_satisfied_general,q03_satisfied_somerville,q04_satisfied_neighborhood,q06a_city_services,q06b_cost_housing,q06c_quality_schools,q06d_trust_police,q06e_sidewalks,...,f08_public,f09_car,f09_walk,f09_bike,f09_public,f10_move_cat1,f10_move_subcat1,f10_move_cat2,f10_move_subcat2,weight
id,,,,,,,,,,,,,,,,,,,,,
7391,2019,10.0,10.0,10.0,10.0,5.0,4.0,4.0,5.0,4.0,...,0.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,16.696060
7392,2019,7.0,7.0,9.0,8.0,4.0,2.0,NaN,4.0,3.0,...,0.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,62.294687
7393,2019,9.0,9.0,1.0,1.0,4.0,1.0,4.0,2.0,1.0,...,0.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN,NaN,28.664828
7394,2019,10.0,9.0,9.0,8.0,5.0,5.0,5.0,5.0,3.0,...,0.0,1.0,1.0,0.0,1.0,Family / Relationship,NaN,NaN,NaN,56.381059
7395,2019,8.0,8.0,7.0,7.0,5.0,3.0,4.0,5.0,1.0,...,0.0,1.0,1.0,0.0,1.0,NaN,NaN,NaN,NaN,26.337525

In [19]:
data.to_csv('../data/processed/survey_data_export.csv', index=True)